START TRANSACTION;

CREATE TABLE "PracticeAreaWorkforceSettings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PracticeAreaId" integer NOT NULL,
    "MinimumActiveLawyers" integer NOT NULL,
    "TargetActiveLawyers" integer NOT NULL,
    "MinimumFutureSlots" integer NOT NULL,
    "HighDemandThreshold" integer NOT NULL,
    "WatchCapacityRatio" double precision NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" integer NOT NULL,
    CONSTRAINT "PK_PracticeAreaWorkforceSettings" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_WorkforceSettings_Ranges" CHECK ("MinimumActiveLawyers" BETWEEN 0 AND 100 AND "TargetActiveLawyers" BETWEEN "MinimumActiveLawyers" AND 200 AND "MinimumFutureSlots" BETWEEN 0 AND 1000 AND "HighDemandThreshold" BETWEEN 0 AND 10000 AND "WatchCapacityRatio" > 0 AND "WatchCapacityRatio" <= 1),
    CONSTRAINT "FK_PracticeAreaWorkforceSettings_Specializations_PracticeAreaId" FOREIGN KEY ("PracticeAreaId") REFERENCES "Specializations" ("SpecializationId") ON DELETE CASCADE
);

CREATE TABLE "WorkforceDemoStates" (
    "Id" integer NOT NULL,
    "ArtifactsJson" jsonb NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_WorkforceDemoStates" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_PracticeAreaWorkforceSettings_PracticeAreaId" ON "PracticeAreaWorkforceSettings" ("PracticeAreaId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20261004061310_AddWorkforcePlanningSettings', '8.0.29');

COMMIT;
