import { availabilityReason, officeToday } from "../../../../api/schedulingApi";
import { field, formatDate, formatTime, primaryButton, secondaryButton, surface, type RecommendationWorkflowModel } from "./recommendationUI";
export function AppointmentApprovalForm({ workflow: w }: { workflow: RecommendationWorkflowModel }) {
  if (!w.result || !w.selected) return null;
  return <form id="appointment-approval" aria-label="Appointment details" onSubmit={w.approve} className={`${surface} space-y-5`}>
    <div><p className="text-xs font-bold uppercase tracking-wider text-amber-800">Human approval required</p><h3 data-recommendation-focus tabIndex={-1} className="mt-2 text-xl font-bold focus:outline-none">Appointment Details</h3><p className="mt-2 text-sm text-slate-500">Confirm the selected client and choose a real available appointment slot. The system validates all booking details before creating the appointment.</p></div>
    <p className="rounded-lg bg-slate-50 p-3 text-sm"><span className="text-slate-500">Selected Lawyer</span><strong className="mt-1 block">{w.selected.fullName}</strong></p>
    <div className="grid gap-5 sm:grid-cols-2">
      <div className="space-y-2"><p className="text-sm font-semibold">Client</p><p className="text-sm">{w.selectedClient?.name || 'Select a client above before continuing.'}</p><p className="break-all text-xs text-slate-500">{w.selectedClient?.email}</p><p className="text-xs text-slate-500">Use Change Client in the intake summary to review another client.</p></div>
      <div className="space-y-4">{w.result.date ? <div className="text-sm"><p className="font-semibold">Appointment Date</p><p className="mt-2">{formatDate(w.result.date)}</p><button type="button" disabled={w.approving || w.reviewSaving} onClick={() => w.clearWorkflow(true)} className="mt-1 min-h-11 text-xs font-semibold text-amber-800 underline focus-visible:outline-2 focus-visible:outline-amber-600">Rerun for Another Date</button></div> : <label className="block text-sm font-semibold">Appointment date<input aria-label="Appointment date" required disabled={w.approving || w.reviewSaving} type="date" min={officeToday()} value={w.bookingDate} onChange={event => w.changeBookingDate(event.target.value)} className={field} /><span className="mt-2 block text-xs font-normal text-slate-500">Availability was not filtered during ranking. Choose a future date and an available slot.</span></label>}
        <label className="block text-sm font-semibold">Available slot<select aria-label="Available slot" required value={w.slotId} onChange={event => w.setSlotId(event.target.value)} disabled={!w.bookingDate || w.slotsLoading || w.approving} className={field}><option value="">{!w.bookingDate ? "Choose a date first" : w.slotsLoading ? "Loading available times..." : w.slots.length ? "Choose an available time" : "No available times on this date"}</option>{w.slots.map(slot => <option key={slot.slotId} value={slot.slotId}>{formatTime(slot.startTime)}–{formatTime(slot.endTime)}</option>)}</select></label>
        {w.bookingDate && !w.slotsLoading && w.slots.length === 0 && <p role="status" className="text-sm text-slate-500">{availabilityReason(w.slotReason)}</p>}
        {w.bookingDate && <button type="button" disabled={w.approving || w.slotsLoading} onClick={w.retrySlots} className="min-h-11 text-xs font-semibold text-amber-800 underline focus-visible:outline-2 focus-visible:outline-amber-600">Refresh Available Slots</button>}
      </div>
    </div>
    <div className="flex flex-wrap gap-3 border-t border-slate-100 pt-5"><button type="button" disabled={w.approving || w.reviewSaving} onClick={w.backToReview} className={secondaryButton}>Back to Review</button><button disabled={w.approving || w.reviewSaving || w.slotsLoading || !w.customerId || !w.slotId} className={primaryButton}>{w.approving ? "Creating appointment..." : "Approve & Create Appointment"}</button></div>
  </form>;
}
