import type { RecommendationResult } from "../../../../api/recommendationsApi";
const summaries: Record<string, string> = { client_selected: "Client selected by administrator", lawyer_selected: "Lawyer selected by administrator", appointment_review_started: "Appointment review started", received: "Requirement submitted", snapshot_loaded: "Verified catalog and candidate snapshot loaded", parse_requirement: "AI interpretation completed", validate_category: "Catalog validation completed", search_lawyers: "Eligible candidates retrieved", rank_candidates: "Ranking completed", validate_recommendations: "Agent results validated", backend_validation: "Recommendations revalidated against the database", await_human_approval: "Awaiting administrator review", human_approval: "Appointment approved by administrator", create_booking: "Appointment created", failed: "Analysis failed" };
export function WorkflowDetails({ result }: { result: RecommendationResult }) {
  const events = result.trace.filter(event => summaries[event.step]);
  return <details className="rounded-lg border border-slate-200 bg-white p-4 text-sm"><summary className="cursor-pointer py-1 font-semibold text-slate-700 focus-visible:outline-2 focus-visible:outline-amber-600">View Workflow Details</summary>
    <dl className="mt-4 grid gap-3 text-xs text-slate-600 sm:grid-cols-2"><div className="min-w-0"><dt className="font-semibold">Workflow ID</dt><dd className="mt-1 break-all">{result.workflowId}</dd></div>{result.clientId != null && <div><dt className="font-semibold">Client ID</dt><dd className="mt-1">{result.clientId}</dd></div>}<div><dt className="font-semibold">Status</dt><dd className="mt-1">{result.status.replaceAll("_", " ")}</dd></div>{events.find(event => event.step === "received") && <div><dt className="font-semibold">Created time</dt><dd className="mt-1">{new Date(events.find(event => event.step === "received")!.timestamp).toLocaleString()}</dd></div>}</dl>
    <ol className="mt-4 space-y-3 border-t border-slate-100 pt-4 text-xs">{events.map((event, index) => <li key={`${event.step}-${index}`} className="flex flex-wrap justify-between gap-1"><span className="text-slate-700">{summaries[event.step]}</span><time className="text-slate-500" dateTime={event.timestamp}>{new Date(event.timestamp).toLocaleString()}</time></li>)}</ol>
  </details>;
}
