const fs=require('fs'),path=require('path'),cp=require('child_process');const {chromium}=require('../../../frontend/node_modules/playwright');
const R=process.cwd(),E=path.join(R,'qmse-output/completion-20261008/evidence'),cfg=JSON.parse(fs.readFileSync('/private/tmp/qmse-completion-control/settings.json'));const previous=JSON.parse(fs.readFileSync(path.join(E,'integrated-final-http.json'))),creation=JSON.parse(fs.readFileSync(path.join(E,'integrated-http.json'))).find(x=>x.method==='POST'&&x.url.startsWith('/api/documentation-requests'));const id=creation.output.requestId;const records=[],steps=[];let b;
async function shot(p,n){await p.waitForTimeout(500);await p.screenshot({path:path.join(E,n+'.png')});fs.writeFileSync(path.join(E,n+'.txt'),await p.locator('body').innerText());steps.push({at:new Date().toISOString(),step:n});}
function observe(p){p.on('response',async r=>{if(r.url().startsWith('http://127.0.0.1:55443/api/')&&!r.url().includes('/auth/'))try{records.push({at:new Date().toISOString(),method:r.request().method(),url:r.url().replace('http://127.0.0.1:55443',''),status:r.status(),output:await r.json(),via:'real application UI'})}catch{}});}
(async()=>{let result={status:'BLOCKED',request_id:id,scope:'Real Flutter web, ASP.NET Core, PostgreSQL, actual deterministic FastAPI clerk ranking, React human review; Gemini not used in this workflow'};try{
 b=await chromium.launch({headless:true});const web=await b.newPage({viewport:{width:1100,height:900}});observe(web);
 await web.goto('http://127.0.0.1:55447/login');await web.locator('#email').fill('qmse-clerk@example.test');await web.locator('#password').fill(cfg.password);await web.getByRole('button',{name:'Sign In',exact:true}).click();await web.getByRole('button',{name:'Review Case'}).first().waitFor();await shot(web,'e2e-12-react-assigned-case');
 await web.getByRole('button',{name:'Review Case'}).first().click();await web.locator('select').last().selectOption('COMPLETED');await web.getByText(`Case #${id} status updated to COMPLETED.`,{exact:true}).waitFor();await shot(web,'e2e-13-react-completed');
 const c=await b.newContext({viewport:{width:1100,height:900},storageState:'/private/tmp/qmse-completion-control/mobile-state.json'});const p=await c.newPage();observe(p);await p.goto('http://127.0.0.1:55448');await p.locator('flt-semantics-placeholder').waitFor({timeout:30000});await p.locator('flt-semantics-placeholder').evaluate(x=>x.click());await p.getByRole('button',{name:/My Requests/}).click();await p.getByText(/Affidavit & Notary Services/).first().click();await p.waitForTimeout(800);const text=await p.locator('body').innerText();if(!text.includes('COMPLETED'))throw Error('Flutter did not show COMPLETED');await shot(p,'e2e-14-flutter-completed');
 const sql=`select d."RequestId",d."CustomerId",d."ClerkId",d."Status",count(f."FileId") as attachments,sum(octet_length(f."FileContents")) as stored_bytes from "DocumentationRequests" d left join "DocumentFiles" f on f."RequestId"=d."RequestId" where d."RequestId"=${id} group by d."RequestId";`;
 const q=cp.execFileSync('/opt/homebrew/bin/psql',['-h','127.0.0.1','-p','55446','-U','qmse_completion','-d','qmse_workflow','-c',sql],{encoding:'utf8'});fs.writeFileSync(path.join(E,'integrated-final-database.log'),q);if(!q.includes('COMPLETED')||!q.match(/\|\s*3\s*\|/))throw Error('Final database state did not match 3 attachments/COMPLETED');
 result={...result,status:'PASS',completed_utc:new Date().toISOString(),checks:['Flutter authenticates and creates real request','Flutter sends genuine bundled NIC PDF via multipart; server stores bytes','Two additional genuine sample files uploaded through real API','FastAPI ranks actual DB clerk and requires human approval','Admin assigns actual ClerkId verified against normalized AI identity','React clerk updates actual request to COMPLETED','Flutter displays COMPLETED after reading API','PostgreSQL verifies 3 stored binary attachments and assigned clerk']};
 console.log(JSON.stringify(result));
 }catch(e){result.reason=e.message;console.error(e.stack)}finally{await new Promise(r=>setTimeout(r,300));fs.writeFileSync(path.join(E,'integrated-completion-http.json'),JSON.stringify(records,null,2));fs.writeFileSync(path.join(E,'integrated-completion-steps.json'),JSON.stringify(steps,null,2));fs.writeFileSync(path.join(E,'integrated-result.json'),JSON.stringify(result,null,2));if(b)await b.close();}})();
