const fs=require('fs'),path=require('path');const {chromium}=require('../../../frontend/node_modules/playwright');
const records=[],steps=[];const cfg=JSON.parse(fs.readFileSync('/private/tmp/qmse-completion-control/settings.json'));const R=process.cwd(),E=path.join(R,'qmse-output/completion-20261008/evidence');
(async()=>{const b=await chromium.launch({headless:true});const c=await b.newContext({viewport:{width:1100,height:900},storageState:'/private/tmp/qmse-completion-control/mobile-state.json'});const p=await c.newPage();p.on('response',async r=>{if(r.url().startsWith('http://127.0.0.1:55443/api/')){try{const d=await r.json();if(d.token)d.token='[REDACTED]';records.push({at:new Date().toISOString(),method:r.request().method(),url:r.url().replace('http://127.0.0.1:55443',''),status:r.status(),output:d,via:'actual Flutter UI'});}catch{}}});
async function shot(page,name){await page.waitForTimeout(700);await page.screenshot({path:path.join(E,name+'.png')});fs.writeFileSync(path.join(E,name+'.txt'),await page.locator('body').innerText());steps.push({at:new Date().toISOString(),step:name});}
async function api(method,url,data,token,ai=false){const response=await fetch((ai?'http://127.0.0.1:55444':'http://127.0.0.1:55443')+url,{method,headers:{'Content-Type':'application/json',...(ai?{'X-AI-Service-Key':cfg.key}:token?{Authorization:'Bearer '+token}:{})},body:data?JSON.stringify(data):undefined});const result=await response.json();const copy=JSON.parse(JSON.stringify(result));if(copy.token)copy.token='[REDACTED]';records.push({at:new Date().toISOString(),method,url,status:response.status,input:url.includes('login')?'[REDACTED LOGIN]':data,output:copy,via:ai?'real FastAPI':'real API'});if(!response.ok)throw Error(url+' status '+response.status);return result;}
try{
await p.goto('http://127.0.0.1:55448');await p.waitForTimeout(2400);await p.locator('flt-semantics-placeholder').waitFor({timeout:30000});await p.locator('flt-semantics-placeholder').evaluate(x=>x.click());await p.waitForTimeout(500);
console.log('HOME',await p.locator('body').innerText());await p.getByRole('button',{name:/My Requests/}).click();await p.waitForTimeout(900);console.log('LIST',await p.locator('body').innerText());await p.screenshot({path:path.join(E,'e2e-07-flutter-my-requests.png')});
console.log('BUTTONS',await p.locator('[role=button]').evaluateAll(x=>x.map(e=>e.innerText)));fs.writeFileSync(path.join(E,'flutter-requests-dom.html'),await p.locator('body').innerHTML());
await p.getByText(/Affidavit & Notary Services/).first().click();await p.waitForTimeout(800);console.log('DETAIL',await p.locator('body').innerText());await p.screenshot({path:path.join(E,'e2e-08-flutter-request-details.png')});
await p.getByRole('button',{name:'Upload Doc',exact:true}).click();await p.waitForTimeout(500);console.log('UPLOAD',await p.locator('body').innerText());await p.screenshot({path:path.join(E,'e2e-09-flutter-upload-picker.png')});
await p.getByRole('button',{name:/Use Sample: National Identity Card/}).click();await shot(p,'e2e-10-flutter-uploaded');console.log('AFTER UPLOAD',await p.locator('body').innerText());
const created=JSON.parse(fs.readFileSync(path.join(E,'integrated-http.json'))).find(x=>x.method==='POST'&&x.url.startsWith('/api/documentation-requests'));const id=created.output.requestId;
const staff=await api('POST','/api/auth/login',{email:'qmse-admin@example.test',password:cfg.password});const token=staff.token;
// Remaining legitimate synthetic attachments use the same real sample-upload endpoint.
for(const name of ['Completed_Affidavit_Draft.pdf','Witness_Details.pdf'])await api('POST',`/api/documentation-requests/${id}/sample-file?sampleName=${name}`,null,token);
const doc=await api('GET',`/api/documentation-requests/${id}`,null,token);if(doc.documentFiles.length!==3)throw Error('Expected exactly 3 persisted attachments');
const candidate=await api('POST','/clerk/recommend',{case_id:String(id),service_type:'AFFIDAVIT'},null,true);const clerks=await api('GET','/api/clerks',null,token);const chosen=candidate.recommendations.find(x=>clerks.some(k=>('CLK-'+String(k.clerkId).padStart(3,'0')===x.clerk_id || String(k.clerkId)===String(x.clerk_id)) && k.fullName===x.name));if(!chosen)throw Error('AI must recommend an actual isolated DB clerk, no fallback identity accepted');
await api('POST',`/api/documentation-requests/${id}/assign-clerk`,{clerkId:clerks.find(k=>k.fullName===chosen.name).clerkId},token);
const web=await b.newPage({viewport:{width:1100,height:900}});web.on('response',async r=>{if(r.url().startsWith('http://127.0.0.1:55443/api/documentation-requests')){try{records.push({at:new Date().toISOString(),via:'actual React UI',method:r.request().method(),url:r.url().replace('http://127.0.0.1:55443',''),status:r.status(),output:await r.json()})}catch{}}});
await web.goto('http://127.0.0.1:55447/login');await web.locator('#email').fill('qmse-clerk@example.test');await web.locator('#password').fill(cfg.password);await web.getByRole('button',{name:'Sign In',exact:true}).click();await web.waitForTimeout(1000);console.log('WEB',await web.locator('body').innerText());await shot(web,'e2e-11-react-clerk-queue');
console.log('WEB BUTTONS',await web.getByRole('button').allTextContents());

}catch(e){console.error(e.stack)}finally{await new Promise(r=>setTimeout(r,300));fs.writeFileSync(path.join(E,'integrated-final-http.json'),JSON.stringify(records,null,2));fs.writeFileSync(path.join(E,'integrated-final-steps.json'),JSON.stringify(steps,null,2));await b.close()}})();
