using LegalService.API.Data;
using LegalService.API.DTOs.Appointments;
using LegalService.API.DTOs.Scheduling;
using LegalService.API.Infrastructure;
using LegalService.API.Models.Entities;
using LegalService.API.Services;
using LegalService.API.Services.Scheduling;
using LegalService.API.Services.Workforce;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;
namespace LegalService.Tests;
public sealed class RecurringSchedulingTests
{
    internal sealed class Clock : TimeProvider { public DateTimeOffset Now = new(2030, 1, 7, 2, 30, 0, TimeSpan.Zero); public override DateTimeOffset GetUtcNow() => Now; }
    internal sealed class Fixture : IAsyncDisposable
    {
        public ApplicationDbContext Db; public Clock Time = new(); public AvailabilityService Availability; public LawyerScheduleService Schedules;
        public Guid Id = Guid.NewGuid(); public Guid Customer = Guid.Parse("00000000-0000-0000-0000-00000000002a"); public DateOnly Date = new(2030, 1, 14);
        public Fixture(DbContextOptions<ApplicationDbContext>? options = null) { Db = new(options ?? new DbContextOptionsBuilder<ApplicationDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options); Availability = new(Db, Time); Schedules = new(Db, Availability); }
        public async Task Seed() { if (!await Db.Specializations.AnyAsync(s => s.SpecializationId == 1)) Db.Specializations.Add(new() { SpecializationId = 1, Name = "Property" }); Db.Users.Add(new() { UserId = 42, Role = "Customer", Email = "customer@test.local", Name = "Customer" }); Db.Lawyers.Add(new() { LawyerId = Id, Name = "Practitioner", Status = "Active", LicenseNumber = "TEST-SCHED", LawyerSpecializations = [new() { SpecializationId = 1 }] }); Db.LawyerWorkingSchedules.Add(new() { LawyerId = Id, DayOfWeek = DayOfWeek.Monday, IsWorkingDay = true, StartTime = new(9, 0), EndTime = new(12, 0) }); await Db.SaveChangesAsync(); }
        public AppointmentService Booking() => new(Db, NullLogger<AppointmentService>.Instance, Availability);
        public async Task<Appointment> Occupy(string status = "Confirmed", TimeOnly? start = null, TimeOnly? end = null, DateOnly? date = null) { var window = new LawyerAvailability { AvailabilityId = Guid.NewGuid(), LawyerId = Id, Date = date ?? Date, StartTime = start ?? new(10, 0), EndTime = end ?? new(10, 30) }; var slot = new AvailabilitySlot { SlotId = Guid.NewGuid(), LawyerAvailability = window, StartTime = window.StartTime, EndTime = window.EndTime, IsBooked = true }; var appointment = new Appointment { AppointmentId = Guid.NewGuid(), LawyerId = Id, CustomerId = Customer, AvailabilitySlot = slot, Status = status, CreatedAt = Time.Now.UtcDateTime }; Db.Appointments.Add(appointment); await Db.SaveChangesAsync(); return appointment; }
        public BookAppointmentRequest Request(TimeOnly start, TimeOnly end) => new() { LawyerId = Id, CustomerId = Customer, SlotId = AvailabilityService.SlotId(Id, Date, start, end) };
        public ScheduleRequest Schedule() => new() { Days = Enumerable.Range(0, 7).Select(day => new WorkingDayDto((DayOfWeek)day, day == 1, new(9, 0), new(12, 0))).ToList() };
        public ValueTask DisposeAsync() => Db.DisposeAsync();
    }
    [Fact] public async Task WorkingDayGeneratesSlotsWithoutPersistingFutureRecords() { await using var f = new Fixture(); await f.Seed(); var result = await f.Availability.GetAsync(f.Id, f.Date); Assert.True(result.WorkingDay); Assert.Equal(6, result.AvailableSlots.Count); Assert.Equal(new TimeOnly(9, 0), result.AvailableSlots[0].Start); Assert.Empty(f.Db.AvailabilitySlots); Assert.Empty(f.Db.LawyerAvailabilities); }
    [Fact] public async Task NonWorkingDayReturnsReason() { await using var f = new Fixture(); await f.Seed(); var result = await f.Availability.GetAsync(f.Id, f.Date.AddDays(1)); Assert.False(result.WorkingDay); Assert.Empty(result.AvailableSlots); Assert.Equal("NOT_WORKING_DAY", result.Reason); }
    [Theory] [InlineData(15, 12)] [InlineData(45, 4)] [InlineData(60, 3)] [InlineData(240, 0)] public async Task DurationControlsGeneration(int duration, int count) { await using var f = new Fixture(); await f.Seed(); (await f.Db.Lawyers.FindAsync(f.Id))!.DefaultAppointmentDurationMinutes = duration; await f.Db.SaveChangesAsync(); Assert.Equal(count, (await f.Availability.GetAsync(f.Id, f.Date)).AvailableSlots.Count); }
    [Fact] public async Task TodayUsesOfficeTimeAndExcludesPastStarts() { await using var f = new Fixture(); await f.Seed(); f.Time.Now = new(2030, 1, 7, 4, 40, 0, TimeSpan.Zero); var result = await f.Availability.GetAsync(f.Id, new(2030, 1, 7)); Assert.Equal(3, result.AvailableSlots.Count); Assert.Equal(new TimeOnly(10, 30), result.AvailableSlots[0].Start); }
    [Theory] [InlineData(true, 0)] [InlineData(false, 4)] public async Task LeaveSubtractsFullOrPartialIntervals(bool full, int expected) { await using var f = new Fixture(); await f.Seed(); await f.Schedules.SaveLeaveAsync(f.Id, null, new() { StartDateTime = f.Date.ToDateTime(full ? TimeOnly.MinValue : new(10, 0)), EndDateTime = full ? f.Date.AddDays(1).ToDateTime(TimeOnly.MinValue) : f.Date.ToDateTime(new(11, 0)), Reason = "Court", IsFullDay = full }); var day = await f.Availability.GetAsync(f.Id, f.Date); Assert.Equal(expected, day.AvailableSlots.Count); if (full) Assert.Equal("ON_LEAVE", day.Reason); }
    [Theory] [InlineData("Cancelled", 6)] [InlineData("Rejected", 6)] [InlineData("Confirmed", 5)] [InlineData("Requested", 5)] [InlineData("Rescheduled", 5)] [InlineData("Completed", 5)] public async Task ActualStatusesDetermineOccupancy(string status, int count) { await using var f = new Fixture(); await f.Seed(); await f.Occupy(status); Assert.Equal(count, (await f.Availability.GetAsync(f.Id, f.Date)).AvailableSlots.Count); }
    [Fact] public async Task PartialOverlapBlocksBothSlotsButAdjacentIntervalsRemain() { await using var f = new Fixture(); await f.Seed(); await f.Occupy(start: new(10, 15), end: new(10, 45)); var day = await f.Availability.GetAsync(f.Id, f.Date); Assert.Equal(4, day.AvailableSlots.Count); Assert.Contains(day.AvailableSlots, s => s.Start == new TimeOnly(9, 30)); Assert.Contains(day.AvailableSlots, s => s.Start == new TimeOnly(11, 0)); }
    [Fact] public async Task InactiveLawyerCannotBeBooked() { await using var f = new Fixture(); await f.Seed(); (await f.Db.Lawyers.FindAsync(f.Id))!.Status = "Inactive"; await f.Db.SaveChangesAsync(); Assert.Empty((await f.Availability.GetAsync(f.Id, f.Date)).AvailableSlots); await Assert.ThrowsAsync<ApiException>(() => f.Booking().BookAppointmentAsync(f.Request(new(9, 0), new(9, 30)))); }
    [Fact] public async Task ConflictingLeaveReturnsAppointmentDataAndNeverCancels() { await using var f = new Fixture(); await f.Seed(); var existing = await f.Occupy(); var error = await Assert.ThrowsAsync<ApiException>(() => f.Schedules.SaveLeaveAsync(f.Id, null, new() { StartDateTime = f.Date.ToDateTime(new(10, 15)), EndDateTime = f.Date.ToDateTime(new(11, 0)), Reason = "Court" })); Assert.Equal(409, error.Status); Assert.Equal(existing.AppointmentId, Assert.Single(Assert.IsType<AppointmentConflict[]>(error.Conflicts)).AppointmentId); Assert.Empty(f.Db.LawyerUnavailabilities); Assert.Equal("Confirmed", existing.Status); }
    [Fact] public async Task AdjacentLeaveCanBeCreatedEditedAndDeleted() { await using var f = new Fixture(); await f.Seed(); await f.Occupy(); var leave = await f.Schedules.SaveLeaveAsync(f.Id, null, new() { StartDateTime = f.Date.ToDateTime(new(10, 30)), EndDateTime = f.Date.ToDateTime(new(11, 0)), Reason = "Training" }); await f.Schedules.SaveLeaveAsync(f.Id, leave.Id, new() { StartDateTime = f.Date.ToDateTime(new(11, 0)), EndDateTime = f.Date.ToDateTime(new(12, 0)), Reason = "Other" }); await f.Schedules.DeleteLeaveAsync(f.Id, leave.Id); Assert.Empty(f.Db.LawyerUnavailabilities); }
    [Theory] [InlineData("duplicate")] [InlineData("overlap")] [InlineData("duration")] public async Task InvalidSchedulesAreRejected(string kind) { await using var f = new Fixture(); await f.Seed(); var value = f.Schedule(); if (kind == "duplicate") value.Days[0] = value.Days[1]; if (kind == "overlap") value.Days[1] = value.Days[1] with { EndTime = new(8, 0) }; if (kind == "duration") value.AppointmentDurationMinutes = 10; Assert.Equal(400, (await Assert.ThrowsAsync<ApiException>(() => f.Schedules.SaveAsync(f.Id, value))).Status); }
    [Fact] public async Task ScheduleSaveIsUniqueAndProtectsExistingAppointments() { await using var f = new Fixture(); await f.Seed(); await f.Schedules.SaveAsync(f.Id, f.Schedule()); await f.Schedules.SaveAsync(f.Id, f.Schedule()); Assert.Equal(7, await f.Db.LawyerWorkingSchedules.CountAsync()); await f.Occupy(); var value = f.Schedule(); value.Days[1] = value.Days[1] with { IsWorkingDay = false }; Assert.Equal(409, (await Assert.ThrowsAsync<ApiException>(() => f.Schedules.SaveAsync(f.Id, value))).Status); }
    [Theory] [InlineData("outside")] [InlineData("leave")] [InlineData("booked")] [InlineData("grid")] [InlineData("customer")] public async Task BookingRevalidatesAllSelectionFacts(string reason) { await using var f = new Fixture(); await f.Seed(); var request = f.Request(new(10, 0), new(10, 30)); if (reason == "outside") request = f.Request(new(8, 0), new(8, 30)); if (reason == "grid") request = f.Request(new(10, 15), new(10, 45)); if (reason == "customer") request.CustomerId = Guid.NewGuid(); if (reason == "booked") await f.Occupy(); if (reason == "leave") await f.Schedules.SaveLeaveAsync(f.Id, null, new() { StartDateTime = f.Date.ToDateTime(new(10, 0)), EndDateTime = f.Date.ToDateTime(new(11, 0)), Reason = "Leave" }); var error = await Assert.ThrowsAsync<ApiException>(() => f.Booking().BookAppointmentAsync(request)); Assert.Equal(reason == "customer" ? 400 : 409, error.Status); }
    [Fact] public async Task ValidBookingCreatesOneSnapshotAndStaleSelectionFails() { await using var f = new Fixture(); await f.Seed(); var request = f.Request(new(10, 0), new(10, 30)); var booked = await f.Booking().BookAppointmentAsync(request); Assert.Equal("Requested", booked.Status); Assert.Single(f.Db.AvailabilitySlots); Assert.Single(f.Db.Appointments); Assert.Equal(409, (await Assert.ThrowsAsync<ApiException>(() => f.Booking().BookAppointmentAsync(request))).Status); }
    [Theory] [InlineData("leave", 4)] [InlineData("appointment", 5)] [InlineData("none", 6)] public async Task WorkforceCapacityUsesScheduleAndSubtractsOccupancy(string scenario, int expected) { await using var f = new Fixture(); await f.Seed(); if (scenario == "appointment") await f.Occupy(date: new(2030, 1, 7)); if (scenario == "leave") await f.Schedules.SaveLeaveAsync(f.Id, null, new() { StartDateTime = new(2030, 1, 7, 10, 0, 0), EndDateTime = new(2030, 1, 7, 11, 0, 0), Reason = "Leave" }); var report = await new WorkforceAnalysisService(f.Db, Options.Create(new WorkforceOptions { FutureWindowDays = 1 }), f.Time, f.Availability).AnalyzeAsync(); Assert.Equal(expected, report.PracticeAreas.Single().FutureAvailableSlotCount); }
    [Fact] public async Task UnknownLawyerReturns404() { await using var f = new Fixture(); Assert.Equal(404, (await Assert.ThrowsAsync<ApiException>(() => f.Availability.GetAsync(Guid.NewGuid(), f.Date))).Status); }
}
