import { frontDeskFixture } from './frontDeskFixture';
import { test, expect, type Page } from '@playwright/test';
const root = '/admin/lawyer-matching?workflow=scheduling';
async function setup(page: Page, reason?: string, preferred = false) {
  const dates: string[] = []; const result = { clientId: 42, workflowId: 'scheduling', status: 'AWAITING_APPROVAL', date: preferred ? '2030-01-14' : null, userRequirement: 'Land ownership dispute', parsedRequirement: { categoryId: 1, categoryName: 'Property' }, recommendations: [{ lawyerId: 'lawyer-1', fullName: 'Practitioner', score: 10, yearsExperience: 10, practiceArea: 'Property', reason: 'Practice Area match.' }], warnings: [], trace: [{ step: 'backend_validation', status: 'completed', timestamp: '2026-10-04T08:00:00Z', summary: 'Verified' }] };
  await page.addInitScript(() => { localStorage.setItem('legalease_staff_user', JSON.stringify({ userId: 1, name: 'Admin', role: 'Admin' })); localStorage.setItem('token', 'test-token'); });
  await page.route(/^https?:\/\/[^/]+\/api\//, async route => {
    const url = new URL(route.request().url()); let body: unknown = [];
    if (url.pathname.endsWith('/summary')) body = { activeLawyers: 1, totalLawyers: 1, practiceAreas: 1, legalServices: 1, coverage: [] };
    if (url.pathname.endsWith('/scheduling')) body = result;
    if (url.pathname.endsWith('/customers')) body = [{ customerId: 'customer-1', name: 'Customer', email: 'customer@test.local' }];
    if (url.pathname.endsWith('/available-slots')) { const date = url.searchParams.get('date')!; dates.push(date); body = { date, workingDay: reason !== 'NOT_WORKING_DAY', appointmentDurationMinutes: 30, reason, timeZone: 'Asia/Colombo', availableSlots: reason ? [] : [{ slotId: 'slot-' + date, start: '10:00:00', end: '10:30:00' }] }; }
    await route.fulfill({ json: body });
  });
  await frontDeskFixture(page, () => result); await page.goto(root); return dates;
}
async function appointment(page: Page) { await page.getByRole('button', { name: 'Select Lawyer', exact: true }).click(); await page.getByRole('button', { name: 'Continue to Appointment' }).click(); }
for (const [reason, message] of [['NOT_WORKING_DAY', 'Lawyer does not work on this day'], ['ON_LEAVE', 'Lawyer is unavailable on this date'], ['FULLY_BOOKED', 'All available times are booked']]) test(`booking explains ${reason}`, async ({ page }) => { const dates = await setup(page, reason); await appointment(page); await page.getByLabel('Appointment date', { exact: true }).fill('2030-01-14'); await expect(page.getByText(message, { exact: true })).toBeVisible(); expect(dates).toEqual(['2030-01-14']); await expect(page.getByRole('button', { name: 'Approve & Create Appointment' })).toBeDisabled(); });
test('date fetch updates derived times and clears stale selection', async ({ page }) => { const dates = await setup(page); await expect(page.getByText('Availability Not Filtered.', { exact: true })).toBeVisible(); await appointment(page); await page.getByLabel('Appointment date', { exact: true }).fill('2030-01-14');  const slots = page.getByLabel('Available slot', { exact: true }); await slots.selectOption('slot-2030-01-14'); await expect(page.getByRole('button', { name: 'Approve & Create Appointment' })).toBeEnabled(); await page.getByLabel('Appointment date', { exact: true }).fill('2030-01-15'); await expect(slots.locator('option[value="slot-2030-01-15"]')).toHaveCount(1); await expect(slots).toHaveValue(''); await expect(slots.locator('option[value="slot-2030-01-14"]')).toHaveCount(0); await expect(page.getByRole('button', { name: 'Approve & Create Appointment' })).toBeDisabled(); expect(dates).toEqual(['2030-01-14', '2030-01-15']); });
test('preferred-date recommendation reports system verification', async ({ page }) => { await setup(page, undefined, true); await expect(page.getByText('Availability verified for requested date. Slots are checked again before booking.')).toBeVisible(); await appointment(page); await expect(page.getByLabel('Available slot', { exact: true }).locator('option[value="slot-2030-01-14"]')).toHaveCount(1); await expect(page.getByLabel('Appointment date', { exact: true })).toHaveCount(0); });
