import { test, expect } from '@playwright/test';
const base = process.env.E2E_SCHEDULING_API;
test.afterEach(async ({ page }) => { await page.unrouteAll({ behavior: 'ignoreErrors' }); });
for (const width of [390, 1280]) test(`real scheduling API and lawyer edit at ${width}px`, async ({ page, request }) => {
  test.skip(!base, 'Set E2E_SCHEDULING_API to a locally running updated backend. Read-only; no Gemini request.');
  const login = await request.post(`${base}/api/auth/login`, { data: { email: process.env.E2E_ADMIN_EMAIL, password: process.env.E2E_ADMIN_PASSWORD } }); expect(login.ok()).toBe(true);
  const auth = await login.json();
  await page.addInitScript(data => { localStorage.setItem('legalease_staff_user', JSON.stringify({ userId: data.userId ?? 1, name: data.name ?? 'Admin', role: 'Admin' })); localStorage.setItem('token', data.token); }, auth);
  await page.route(/^https?:\/\/[^/]+\/api\//, async route => { const url = new URL(route.request().url()); const response = await route.fetch({ url: `${base}${url.pathname}${url.search}` }); await route.fulfill({ response }); });
  await page.setViewportSize({ width, height: 900 });
  await page.goto('/admin/lawyer-services/lawyers');
  await page.getByRole('button', { name: 'Edit', exact: true }).first().click();
  await expect(page.getByRole('region', { name: 'Working schedule' })).toContainText('Asia/Colombo');
  await expect(page.getByLabel('Appointment Duration (minutes)')).toHaveValue('30');
  await expect(page.getByRole('button', { name: 'Save Schedule' })).toBeVisible();
  await page.getByRole('button', { name: 'Save Schedule' }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: `../docs/evidence/recurring-scheduling/live-schedule-${width}.png`, fullPage: true });
  expect(await page.getByRole('dialog').evaluate(node => node.scrollWidth <= node.clientWidth + 1)).toBe(true);
});
test('existing lawyer Save Schedule button persists through the real API', async ({ page, request }) => {
  test.skip(!base || process.env.E2E_SCHEDULING_SAVE !== '1', 'Opt in to an unchanged schedule save against the local Development API.');
  expect(base).toMatch(/^http:\/\/127\.0\.0\.1:/);
  const login = await request.post(`${base}/api/auth/login`, { data: { email: process.env.E2E_ADMIN_EMAIL, password: process.env.E2E_ADMIN_PASSWORD } }); expect(login.ok()).toBe(true);
  const auth = await login.json();
  const headers = { Authorization: `Bearer ${auth.token}` };
  const directory = await request.get(`${base}/api/lawyers/search?page=1&pageSize=100`, { headers }); expect(directory.ok()).toBe(true);
  const lawyers: { lawyerId: string; licenseNumber: string }[] = (await directory.json()).items;
  const lawyer = lawyers.filter(l => l.licenseNumber.startsWith('ILS/LAW/')).sort((a, b) => a.licenseNumber.localeCompare(b.licenseNumber))[4];
  expect(lawyer).toBeTruthy();
  const path = `${base}/api/lawyers/${lawyer.lawyerId}/working-schedule`;
  const original = await (await request.get(path, { headers })).json();
  await page.addInitScript(data => { localStorage.setItem('legalease_staff_user', JSON.stringify({ userId: data.userId ?? 1, name: data.name ?? 'Admin', role: 'Admin' })); localStorage.setItem('token', data.token); }, auth);
  await page.route(/^https?:\/\/[^/]+\/api\//, async route => { const url = new URL(route.request().url()); const response = await route.fetch({ url: `${base}${url.pathname}${url.search}` }); await route.fulfill({ response }); });
  await page.goto('/admin/lawyer-services/lawyers');
  await page.getByPlaceholder('Search lawyers by name, license number, qualifications...').fill(lawyer.licenseNumber);
  await expect(page.getByRole('button', { name: 'Edit', exact: true })).toHaveCount(1);
  await page.getByRole('button', { name: 'Edit', exact: true }).click();
  const save = page.getByRole('button', { name: 'Save Schedule' }); await expect(save).toBeEnabled();
  const response = page.waitForResponse(res => res.url().endsWith(`/api/lawyers/${lawyer.lawyerId}/working-schedule`) && res.request().method() === 'PUT');
  await save.click(); expect((await response).status()).toBe(200);
  await expect(page.getByRole('status').filter({ hasText: 'Working schedule saved.' })).toBeVisible();
  const persisted = await (await request.get(path, { headers })).json();
  expect(persisted.days).toEqual(original.days); expect(persisted.appointmentDurationMinutes).toBe(original.appointmentDurationMinutes);
  await page.screenshot({ path: '../docs/evidence/recurring-scheduling/live-schedule-save.png', fullPage: true });
});
