// <auto-generated />
using System;
using LegalService.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LegalService.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LegalService.API.Models.Entities.AgentStep", b =>
                {
                    b.Property<Guid>("StepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InputPayload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("OutputPayload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("StepId");

                    b.HasIndex("WorkflowId");

                    b.ToTable("AgentSteps");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.AgentWorkflow", b =>
                {
                    b.Property<Guid>("WorkflowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ServiceRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("WorkflowId");

                    b.HasIndex("ServiceRequestId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("AgentWorkflows");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.Appointment", b =>
                {
                    b.Property<Guid>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LawyerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SlotId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AppointmentId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LawyerId");

                    b.HasIndex("SlotId")
                        .IsUnique();

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.AppointmentStatusHistory", b =>
                {
                    b.Property<Guid>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("HistoryId");

                    b.HasIndex("AppointmentId");

                    b.ToTable("AppointmentStatusHistories");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.ApprovalDecision", b =>
                {
                    b.Property<Guid>("DecisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApproverId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("DecisionId");

                    b.HasIndex("ApproverId");

                    b.HasIndex("WorkflowId");

                    b.ToTable("ApprovalDecisions");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("AuditLogId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.AvailabilitySlot", b =>
                {
                    b.Property<Guid>("SlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AvailabilityId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("IsBooked")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LawyerId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("SlotId");

                    b.HasIndex("AvailabilityId");

                    b.HasIndex("LawyerId");

                    b.ToTable("AvailabilitySlots");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.Career", b =>
                {
                    b.Property<Guid>("CareerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CareerId");

                    b.ToTable("Careers");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.Clerk", b =>
                {
                    b.Property<Guid>("ClerkId")
                        .HasColumnType("uuid");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ClerkId");

                    b.ToTable("Clerks");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.DocumentFile", b =>
                {
                    b.Property<Guid>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Received");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FileId");

                    b.HasIndex("DocumentStatus");

                    b.HasIndex("RequestId");

                    b.ToTable("DocumentFiles");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.DocumentationRequest", b =>
                {
                    b.Property<Guid>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedClerkId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RequestId");

                    b.HasIndex("AssignedClerkId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ServiceId");

                    b.ToTable("DocumentationRequests");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.DocumentationService", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServiceId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequiredDocuments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ServiceId");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DocumentationServices");

                    b.HasData(
                        new
                        {
                            ServiceId = 1,
                            Description = "Reviewing lease/sales agreements and drafting amendments.",
                            IsActive = true,
                            Name = "Contract Review & Amendment",
                            RequiredDocuments = "[\"Original Contract\",\"Amendment Request Letter\",\"NIC Copy\"]"
                        },
                        new
                        {
                            ServiceId = 2,
                            Description = "Drafting affidavits and arranging official notarization.",
                            IsActive = true,
                            Name = "Affidavit & Notary Services",
                            RequiredDocuments = "[\"NIC\",\"Completed Affidavit Draft\",\"Witness Details\"]"
                        },
                        new
                        {
                            ServiceId = 3,
                            Description = "Drafting General or Special Power of Attorney documents.",
                            IsActive = true,
                            Name = "Power of Attorney Drafting",
                            RequiredDocuments = "[\"NIC of Grantor\",\"NIC of Grantee\",\"Scope of Authority Document\"]"
                        });
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.ExecutionSummary", b =>
                {
                    b.Property<Guid>("SummaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FinalOutcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("SummaryId");

                    b.HasIndex("WorkflowId")
                        .IsUnique();

                    b.ToTable("ExecutionSummaries");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.JobApplication", b =>
                {
                    b.Property<Guid>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CareerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ApplicationId");

                    b.HasIndex("CareerId");

                    b.ToTable("JobApplications");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.Lawyer", b =>
                {
                    b.Property<Guid>("LawyerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LawyerId");

                    b.HasIndex("LicenseNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Lawyers");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.LawyerAvailability", b =>
                {
                    b.Property<Guid>("AvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("LawyerId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("AvailabilityId");

                    b.HasIndex("LawyerId", "Date");

                    b.ToTable("LawyerAvailabilities");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.LawyerLegalService", b =>
                {
                    b.Property<Guid>("LawyerId")
                        .HasColumnType("uuid");

                    b.Property<int>("LegalServiceId")
                        .HasColumnType("integer");

                    b.HasKey("LawyerId", "LegalServiceId");

                    b.HasIndex("LegalServiceId");

                    b.ToTable("LawyerLegalServices");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.LawyerSpecialization", b =>
                {
                    b.Property<Guid>("LawyerId")
                        .HasColumnType("uuid");

                    b.Property<int>("SpecializationId")
                        .HasColumnType("integer");

                    b.HasKey("LawyerId", "SpecializationId");

                    b.HasIndex("SpecializationId");

                    b.ToTable("LawyerSpecializations");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.LegalService", b =>
                {
                    b.Property<int>("LegalServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LegalServiceId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LegalServiceId");

                    b.ToTable("LegalServices");

                    b.HasData(
                        new
                        {
                            LegalServiceId = 1,
                            Category = "Criminal Law",
                            CreatedAt = new DateTime(2026, 9, 2, 12, 0, 30, 347, DateTimeKind.Utc).AddTicks(4129),
                            Description = "Representation and case review for criminal defense cases.",
                            ServiceName = "Criminal Defense Consulting"
                        },
                        new
                        {
                            LegalServiceId = 2,
                            Category = "Family Law",
                            CreatedAt = new DateTime(2026, 9, 2, 12, 0, 30, 347, DateTimeKind.Utc).AddTicks(4142),
                            Description = "Preparation and filing for divorce and child custody.",
                            ServiceName = "Divorce & Custody Filing"
                        },
                        new
                        {
                            LegalServiceId = 3,
                            Category = "Corporate Law",
                            CreatedAt = new DateTime(2026, 9, 2, 12, 0, 30, 347, DateTimeKind.Utc).AddTicks(4144),
                            Description = "Incorporation filings and compliance setup.",
                            ServiceName = "Corporate Registration & Compliance"
                        });
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3a0767c-9b7e-40fb-881c-cb8e2c07df74"),
                            Name = "Customer"
                        },
                        new
                        {
                            Id = new Guid("7f7b3df6-6eb3-4a6c-b7ee-d57be45dc98a"),
                            Name = "Lawyer"
                        },
                        new
                        {
                            Id = new Guid("e81f5cb1-ea60-449e-b9ef-d4924a48045d"),
                            Name = "Clerk"
                        },
                        new
                        {
                            Id = new Guid("15f92271-e0e6-42d8-bf12-cb4b71db3f05"),
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.ServiceRequest", b =>
                {
                    b.Property<Guid>("ServiceRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("PreferredDeadline")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ServiceRequestId");

                    b.HasIndex("CustomerId");

                    b.ToTable("ServiceRequests");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.Specialization", b =>
                {
                    b.Property<int>("SpecializationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SpecializationId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SpecializationId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Specializations");

                    b.HasData(
                        new
                        {
                            SpecializationId = 1,
                            Description = "Defense and prosecutorial assistance in criminal litigation.",
                            Name = "Criminal Law"
                        },
                        new
                        {
                            SpecializationId = 2,
                            Description = "Divorce, child custody, and domestic relationships.",
                            Name = "Family Law"
                        },
                        new
                        {
                            SpecializationId = 3,
                            Description = "Business registration, compliance, and contract drafting.",
                            Name = "Corporate Law"
                        },
                        new
                        {
                            SpecializationId = 4,
                            Description = "Real estate transactions, leases, and title disputes.",
                            Name = "Property Law"
                        });
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.ToolExecution", b =>
                {
                    b.Property<Guid>("ToolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InputData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("OutputData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("StepId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ToolId");

                    b.HasIndex("StepId");

                    b.ToTable("ToolExecutions");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.ValidationResult", b =>
                {
                    b.Property<Guid>("ValidationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Errors")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean");

                    b.Property<string>("RulesChecked")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("ValidationId");

                    b.HasIndex("WorkflowId");

                    b.ToTable("ValidationResults");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.AgentStep", b =>
                {
                    b.HasOne("LegalService.API.Models.Entities.AgentWorkflow", "AgentWorkflow")
                        .WithMany("AgentSteps")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentWorkflow");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.AgentWorkflow", b =>
                {
                    b.HasOne("LegalService.API.Models.Entities.ServiceRequest", "ServiceRequest")
                        .WithOne("AgentWorkflow")
                        .HasForeignKey("LegalService.API.Models.Entities.AgentWorkflow", "ServiceRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServiceRequest");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.Appointment", b =>
                {
                    b.HasOne("LegalService.API.Models.Entities.User", "Customer")
                        .WithMany("Appointments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LegalService.API.Models.Entities.Lawyer", "Lawyer")
                        .WithMany("Appointments")
                        .HasForeignKey("LawyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LegalService.API.Models.Entities.AvailabilitySlot", "AvailabilitySlot")
                        .WithOne("Appointment")
                        .HasForeignKey("LegalService.API.Models.Entities.Appointment", "SlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AvailabilitySlot");

                    b.Navigation("Customer");

                    b.Navigation("Lawyer");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.AppointmentStatusHistory", b =>
                {
                    b.HasOne("LegalService.API.Models.Entities.Appointment", "Appointment")
                        .WithMany("AppointmentStatusHistories")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.ApprovalDecision", b =>
                {
                    b.HasOne("LegalService.API.Models.Entities.User", "Approver")
                        .WithMany("ApprovalDecisions")
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LegalService.API.Models.Entities.AgentWorkflow", "AgentWorkflow")
                        .WithMany("ApprovalDecisions")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentWorkflow");

                    b.Navigation("Approver");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.AuditLog", b =>
                {
                    b.HasOne("LegalService.API.Models.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.AvailabilitySlot", b =>
                {
                    b.HasOne("LegalService.API.Models.Entities.LawyerAvailability", "LawyerAvailability")
                        .WithMany("AvailabilitySlots")
                        .HasForeignKey("AvailabilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegalService.API.Models.Entities.Lawyer", null)
                        .WithMany("AvailabilitySlots")
                        .HasForeignKey("LawyerId");

                    b.Navigation("LawyerAvailability");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.Clerk", b =>
                {
                    b.HasOne("LegalService.API.Models.Entities.User", "User")
                        .WithOne("Clerk")
                        .HasForeignKey("LegalService.API.Models.Entities.Clerk", "ClerkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.DocumentFile", b =>
                {
                    b.HasOne("LegalService.API.Models.Entities.DocumentationRequest", "DocumentationRequest")
                        .WithMany("DocumentFiles")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentationRequest");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.DocumentationRequest", b =>
                {
                    b.HasOne("LegalService.API.Models.Entities.Clerk", "AssignedClerk")
                        .WithMany("DocumentationRequests")
                        .HasForeignKey("AssignedClerkId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LegalService.API.Models.Entities.User", "Customer")
                        .WithMany("DocumentationRequests")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LegalService.API.Models.Entities.DocumentationService", "DocumentationService")
                        .WithMany("DocumentationRequests")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedClerk");

                    b.Navigation("Customer");

                    b.Navigation("DocumentationService");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.ExecutionSummary", b =>
                {
                    b.HasOne("LegalService.API.Models.Entities.AgentWorkflow", "AgentWorkflow")
                        .WithOne("ExecutionSummary")
                        .HasForeignKey("LegalService.API.Models.Entities.ExecutionSummary", "WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentWorkflow");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.JobApplication", b =>
                {
                    b.HasOne("LegalService.API.Models.Entities.Career", "Career")
                        .WithMany("JobApplications")
                        .HasForeignKey("CareerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Career");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.Lawyer", b =>
                {
                    b.HasOne("LegalService.API.Models.Entities.User", "User")
                        .WithOne("Lawyer")
                        .HasForeignKey("LegalService.API.Models.Entities.Lawyer", "LawyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.LawyerAvailability", b =>
                {
                    b.HasOne("LegalService.API.Models.Entities.Lawyer", "Lawyer")
                        .WithMany("LawyerAvailabilities")
                        .HasForeignKey("LawyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lawyer");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.LawyerLegalService", b =>
                {
                    b.HasOne("LegalService.API.Models.Entities.Lawyer", "Lawyer")
                        .WithMany("LawyerLegalServices")
                        .HasForeignKey("LawyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegalService.API.Models.Entities.LegalService", "LegalService")
                        .WithMany("LawyerLegalServices")
                        .HasForeignKey("LegalServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lawyer");

                    b.Navigation("LegalService");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.LawyerSpecialization", b =>
                {
                    b.HasOne("LegalService.API.Models.Entities.Lawyer", "Lawyer")
                        .WithMany("LawyerSpecializations")
                        .HasForeignKey("LawyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegalService.API.Models.Entities.Specialization", "Specialization")
                        .WithMany("LawyerSpecializations")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lawyer");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.ServiceRequest", b =>
                {
                    b.HasOne("LegalService.API.Models.Entities.User", "Customer")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.ToolExecution", b =>
                {
                    b.HasOne("LegalService.API.Models.Entities.AgentStep", "AgentStep")
                        .WithMany("ToolExecutions")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentStep");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.UserRole", b =>
                {
                    b.HasOne("LegalService.API.Models.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegalService.API.Models.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.ValidationResult", b =>
                {
                    b.HasOne("LegalService.API.Models.Entities.AgentWorkflow", "AgentWorkflow")
                        .WithMany("ValidationResults")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentWorkflow");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.AgentStep", b =>
                {
                    b.Navigation("ToolExecutions");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.AgentWorkflow", b =>
                {
                    b.Navigation("AgentSteps");

                    b.Navigation("ApprovalDecisions");

                    b.Navigation("ExecutionSummary");

                    b.Navigation("ValidationResults");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.Appointment", b =>
                {
                    b.Navigation("AppointmentStatusHistories");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.AvailabilitySlot", b =>
                {
                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.Career", b =>
                {
                    b.Navigation("JobApplications");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.Clerk", b =>
                {
                    b.Navigation("DocumentationRequests");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.DocumentationRequest", b =>
                {
                    b.Navigation("DocumentFiles");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.DocumentationService", b =>
                {
                    b.Navigation("DocumentationRequests");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.Lawyer", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("AvailabilitySlots");

                    b.Navigation("LawyerAvailabilities");

                    b.Navigation("LawyerLegalServices");

                    b.Navigation("LawyerSpecializations");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.LawyerAvailability", b =>
                {
                    b.Navigation("AvailabilitySlots");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.LegalService", b =>
                {
                    b.Navigation("LawyerLegalServices");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.ServiceRequest", b =>
                {
                    b.Navigation("AgentWorkflow");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.Specialization", b =>
                {
                    b.Navigation("LawyerSpecializations");
                });

            modelBuilder.Entity("LegalService.API.Models.Entities.User", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ApprovalDecisions");

                    b.Navigation("AuditLogs");

                    b.Navigation("Clerk");

                    b.Navigation("DocumentationRequests");

                    b.Navigation("Lawyer");

                    b.Navigation("ServiceRequests");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
