import { useEffect, useState, useRef } from 'react';
import axios from 'axios';
import { schedulingApi, scheduleError, schedulingErrorMessage, loadedSchedule, nextDate, type WorkingSchedule, type Unavailability, type AppointmentConflict } from '../../api/schedulingApi';
import { WorkingScheduleEditor } from './WorkingScheduleEditor';
const field = 'mt-1 w-full rounded-lg border border-slate-300 p-2 text-sm';
const action = 'rounded-lg bg-amber-500 px-4 py-2 text-sm font-semibold text-slate-950 disabled:opacity-50';
export function LawyerSchedulingPanel({ lawyerId }: { lawyerId: string }) {
  const errorPanel = useRef<HTMLDivElement>(null);
  const mutationPending = useRef(false);
  const [schedule, setSchedule] = useState<WorkingSchedule>(); const [leave, setLeave] = useState<Unavailability[]>([]);
  const [scheduleAttempt, setScheduleAttempt] = useState(0); const [leaveAttempt, setLeaveAttempt] = useState(0);
  const [scheduleLoading, setScheduleLoading] = useState(true); const [leaveLoading, setLeaveLoading] = useState(true);
  const [scheduleLoadError, setScheduleLoadError] = useState(''); const [leaveLoadError, setLeaveLoadError] = useState('');
  const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [conflicts, setConflicts] = useState<AppointmentConflict[]>([]); const [busy, setBusy] = useState(false);
  useEffect(() => { if (errorPanel.current) errorPanel.current.scrollIntoView({ block: "nearest" }); }, [error]);
  const [editing, setEditing] = useState<string | null>(null); const [start, setStart] = useState(''); const [end, setEnd] = useState(''); const [fullDay, setFullDay] = useState(false); const [reason, setReason] = useState('');
  const fail = (cause: unknown) => { setError(schedulingErrorMessage(cause)); setConflicts(axios.isAxiosError(cause) ? cause.response?.data?.conflicts ?? [] : []); };
  useEffect(() => {
    let active = true; const controller = new AbortController();
    // Load independently: a leave failure must not prevent editing a successfully loaded schedule.
    void schedulingApi.schedule(lawyerId, controller.signal).then(value => { if (active) { setSchedule(loadedSchedule(value)); setScheduleLoadError(''); } }).catch(cause => { if (active) setScheduleLoadError(schedulingErrorMessage(cause)); }).finally(() => { if (active) setScheduleLoading(false); });
    return () => { active = false; controller.abort(); };
  }, [lawyerId, scheduleAttempt]);
  useEffect(() => {
    let active = true; const controller = new AbortController();
    void schedulingApi.leave(lawyerId, controller.signal).then(rows => { if (active) { setLeave(rows); setLeaveLoadError(''); } }).catch(cause => { if (active) setLeaveLoadError(schedulingErrorMessage(cause)); }).finally(() => { if (active) setLeaveLoading(false); });
    return () => { active = false; controller.abort(); };
  }, [lawyerId, leaveAttempt]);
  const retrySchedule = () => { setScheduleLoadError(''); setScheduleLoading(true); setScheduleAttempt(value => value + 1); };
  const retryLeave = () => { setLeaveLoadError(''); setLeaveLoading(true); setLeaveAttempt(value => value + 1); };
  const run = async (work: () => Promise<void>) => { if (mutationPending.current) return; mutationPending.current = true; setBusy(true); setError(''); setSuccess(''); setConflicts([]); try { await work(); } catch (cause) { fail(cause); } finally { mutationPending.current = false; setBusy(false); } };
  const edit = (row?: Unavailability) => { setEditing(row?.id ?? 'new'); setFullDay(row?.isFullDay ?? false); setStart(row ? row.isFullDay ? row.startDateTime.slice(0, 10) : row.startDateTime.slice(0, 16) : ''); setEnd(row ? row.isFullDay ? nextDate(row.endDateTime.slice(0, 10), -1) : row.endDateTime.slice(0, 16) : ''); setReason(row?.reason ?? ''); setError(''); setConflicts([]); };
  return <div className="p-6 border-t border-slate-200 space-y-6">
    {error && <div ref={errorPanel} role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-800"><p className="font-semibold">Unable to Save Scheduling Changes</p><p className="mt-1">{error}</p>{conflicts.map(item => <p key={item.appointmentId} className="mt-2 [overflow-wrap:anywhere]">Appointment #{item.appointmentId} · {item.date} · {item.startTime.slice(0, 5)}–{item.endTime.slice(0, 5)}</p>)}{conflicts.length > 0 && <p className="mt-2">Resolve or reschedule these appointments before marking the lawyer unavailable.</p>}</div>}
    {success && <p role="status" className="text-sm text-slate-700">{success}</p>}
    {scheduleLoadError && <div role="alert" className="text-sm text-red-800"><p>{scheduleLoadError}</p><button type="button" className="mt-2 underline" onClick={retrySchedule}>Retry working schedule</button></div>}
    {schedule ? <div className="space-y-3">{schedule.hasConfiguredSchedule === false && <p className="text-sm text-slate-600">No saved working schedule. These are editable defaults; save to apply them.</p>}<WorkingScheduleEditor value={schedule} onChange={setSchedule} disabled={busy || scheduleLoading || !!scheduleLoadError} /><button type="button" className={action} disabled={busy || scheduleLoading || !!scheduleLoadError} onClick={() => void run(async () => { const message = scheduleError(schedule); if (message) throw new Error(message); setSchedule(loadedSchedule(await schedulingApi.saveSchedule(lawyerId, schedule))); setSuccess('Working schedule saved.'); })}>Save Schedule</button></div> : scheduleLoading ? <p className="text-sm text-slate-500">Loading working schedule...</p> : null}
    <section aria-label="Leave and unavailability" className="space-y-3"><div className="flex flex-wrap gap-3 items-center justify-between"><h4 className="font-bold text-slate-900">Leave & Unavailability</h4><button type="button" disabled={busy} onClick={() => edit()} className={action}>+ Add Unavailability</button></div><p className="text-xs text-slate-500">Upcoming unavailability · office time. Existing appointments must be resolved first.</p>
      {leaveLoading && <p className="text-sm text-slate-500">Loading unavailability...</p>}{leaveLoadError && <div role="alert" className="text-sm text-red-800"><p>{leaveLoadError}</p><button type="button" className="mt-2 underline" onClick={retryLeave}>Retry unavailability</button></div>}
      {!leaveLoading && !leaveLoadError && !leave.length && <p className="text-sm text-slate-500">No upcoming unavailability.</p>}{leave.map(row => <div key={row.id} className="rounded-lg border border-slate-200 p-3 flex flex-wrap gap-3 justify-between"><div><p className="text-sm font-semibold">{row.startDateTime.slice(0, 10)} {row.isFullDay ? `to ${nextDate(row.endDateTime.slice(0, 10), -1)} · Full day` : `${row.startDateTime.slice(11, 16)} to ${row.endDateTime.slice(0, 16).replace('T', ' ')}`}</p><p className="text-sm text-slate-500">{row.reason}</p></div><div className="flex gap-3 text-sm"><button type="button" disabled={busy} onClick={() => edit(row)} className="text-amber-800 underline">Edit</button><button type="button" disabled={busy} onClick={() => void run(async () => { await schedulingApi.deleteLeave(lawyerId, row.id); setLeave(await schedulingApi.leave(lawyerId)); setSuccess('Unavailability deleted.'); })} className="text-slate-600 underline">Delete</button></div></div>)}
      {editing && <div className="rounded-lg bg-slate-50 p-4 space-y-3"><label className="flex gap-2 text-sm"><input type="checkbox" checked={fullDay} onChange={event => { setFullDay(event.target.checked); setStart(''); setEnd(''); }} />Full Day</label><div className="grid sm:grid-cols-2 gap-3"><label className="text-sm">Start {fullDay ? 'Date' : 'Date & Time'}<input aria-label="Leave start" className={field} type={fullDay ? 'date' : 'datetime-local'} value={start} onChange={event => setStart(event.target.value)} /></label><label className="text-sm">End {fullDay ? 'Date (inclusive)' : 'Date & Time'}<input aria-label="Leave end" className={field} type={fullDay ? 'date' : 'datetime-local'} value={end} onChange={event => setEnd(event.target.value)} /></label></div><label className="block text-sm">Reason<input aria-label="Leave reason" maxLength={300} value={reason} onChange={event => setReason(event.target.value)} className={field} placeholder="Annual Leave, Court Appearance..." /></label><div className="flex gap-3"><button type="button" disabled={busy} className={action} onClick={() => void run(async () => { if (!start || !end || !reason.trim() || (fullDay ? start > end : start >= end)) throw new Error('Enter a valid period and a reason.'); await schedulingApi.saveLeave(lawyerId, { startDateTime: fullDay ? `${start}T00:00:00` : `${start}:00`, endDateTime: fullDay ? `${nextDate(end)}T00:00:00` : `${end}:00`, reason: reason.trim(), isFullDay: fullDay }, editing === 'new' ? undefined : editing); setLeave(await schedulingApi.leave(lawyerId)); setEditing(null); setSuccess('Unavailability saved.'); })}>Save Unavailability</button><button type="button" disabled={busy} onClick={() => setEditing(null)} className="text-sm text-slate-600">Cancel</button></div></div>}
    </section>
  </div>;
}
