import type { WorkingSchedule } from '../../api/schedulingApi';
const days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
const field = 'rounded-lg border border-slate-300 p-1.5 text-xs min-w-0 w-full disabled:bg-slate-50 disabled:text-slate-400';
export function WorkingScheduleEditor({ value, onChange, disabled = false }: { value: WorkingSchedule; onChange: (value: WorkingSchedule) => void; disabled?: boolean }) {
  const update = (dayOfWeek: number, changes: object) => onChange({ ...value, days: value.days.map(day => day.dayOfWeek === dayOfWeek ? { ...day, ...changes } : day) });
  return <section aria-label="Working schedule" className="space-y-3 text-slate-900"><h4 className="font-bold">Working Schedule</h4><p className="text-xs text-slate-500">Recurring weekly hours · {value.timeZone ?? 'Asia/Colombo'}. Leave and appointments reduce bookable time.</p>
    {[1, 2, 3, 4, 5, 6, 0].map(number => { const day = value.days.find(item => item.dayOfWeek === number)!; return <div key={number} className="grid grid-cols-[0.8fr_1.1fr_1.1fr] gap-2 items-center border-b border-slate-100 pb-2"><label className="text-xs sm:text-sm flex items-center gap-2"><input type="checkbox" aria-label={`${days[number]} working`} disabled={disabled} checked={day.isWorkingDay} onChange={event => update(number, { isWorkingDay: event.target.checked })} />{days[number]}</label><input type="time" aria-label={`${days[number]} start`} className={field} disabled={disabled || !day.isWorkingDay} value={day.startTime.slice(0, 5)} onChange={event => update(number, { startTime: event.target.value })} /><input type="time" aria-label={`${days[number]} end`} className={field} disabled={disabled || !day.isWorkingDay} value={day.endTime.slice(0, 5)} onChange={event => update(number, { endTime: event.target.value })} /></div>; })}
    <label className="block text-sm font-semibold">Appointment Duration (minutes)<input type="number" min="15" max="240" step="1" disabled={disabled} className={`${field} mt-2`} value={value.appointmentDurationMinutes} onChange={event => onChange({ ...value, appointmentDurationMinutes: Number(event.target.value) })} /></label>
  </section>;
}
