"""
app/schemas/document.py

Pydantic models for document analysis, validation results, and the
verification summary report shown to clients.
"""

from __future__ import annotations
from pydantic import BaseModel, Field


class DocumentAnalysis(BaseModel):
    """
    Structured output from Gemini after analysing a single uploaded file.

    IMPORTANT: classification_confidence is a score Gemini produces.
    Python code in document_validation.py applies the threshold to make
    the accept/reject decision — Gemini cannot override it.
    """

    document_type: str = Field(
        description="What type of document this appears to be (e.g. 'NIC', 'Proof of Address'). "
                    "Use 'unknown' if classification is not possible."
    )
    classification_confidence: float = Field(
        ge=0.0, le=1.0,
        description="Confidence score 0.0–1.0 for the document_type classification."
    )
    readable: bool = Field(
        description="True if the document text/content is legible and extractable."
    )
    extracted_fields: dict = Field(
        default_factory=dict,
        description="Key fields successfully extracted (e.g. {'name': 'John Silva', 'id_number': '123456789V'})."
    )
    missing_fields: list[str] = Field(
        default_factory=list,
        description="Fields that were expected but could not be extracted."
    )
    issues: list[str] = Field(
        default_factory=list,
        description="Specific problems found (e.g. 'image too blurry', 'document rotated')."
    )
    requires_human_review: bool = Field(
        default=False,
        description="True when confidence is in the medium range (0.70–0.89) — accepted but flagged."
    )
    analysis_summary: str = Field(
        description="One-sentence human-readable summary of the analysis result."
    )


class DocumentValidationResult(BaseModel):
    """Result of the Python-side validation logic applied to a DocumentAnalysis."""

    decision: str = Field(
        description="One of: ACCEPTED | ACCEPTED_WITH_FLAG | REJECTED | HUMAN_REVIEW"
    )
    doc_type: str
    file_id: int
    reason: str = Field(description="Explanation of why this decision was made.")
    retry_count: int = Field(description="How many times this document has been attempted.")
    client_message: str = Field(
        description="The message to send to the client (either confirmation or re-ask instruction)."
    )


# ---------------------------------------------------------------------------
# Document Verification Summary (shown to client after all docs accepted)
# ---------------------------------------------------------------------------

class DocumentSummaryItem(BaseModel):
    """Summary entry for a single verified document."""

    doc_type: str
    status: str = Field(description="'accepted' or 'accepted_with_flag'")
    confidence_percent: int = Field(description="Confidence as integer percentage (e.g. 96).")
    verified_fields: list[str] = Field(
        default_factory=list,
        description="Names of fields successfully extracted and verified."
    )
    attempts: int = Field(description="Total upload attempts (including the successful one).")
    flagged: bool = Field(default=False)
    flag_reason: str | None = Field(
        default=None,
        description="Short description of why the document was flagged (if flagged=True)."
    )


class DocumentSummaryReport(BaseModel):
    """
    Complete verification summary generated after all required documents are accepted.
    Stored in state.audit_log and shown to the client in chat.
    """

    service_name: str
    request_id: int
    total_required: int
    total_accepted: int
    total_flagged: int
    documents: list[DocumentSummaryItem]
    ready_for_assignment: bool
    summary_message: str = Field(
        description="Full human-readable summary message generated by Gemini, shown to client."
    )
